// https://dbdiagram.io/d/63b1a3057d39e42284e85883
Table users {
  id int [pk]
  username varchar
  password varchar
  email varchar
  phone_no varchar
  first_name varchar
  last_name varchar
  avatar int
  address_id int
  token varchar
  verified bit
  enabled bit
  created_at bigint
  last_modified bigint
}

Table roles {
  id int [pk]
  name varchar
  desc varchar
}

Table user_roles {
  id int [pk]
  username varchar
  name varchar
  role_id int
}

// related to products
Table brands {
  id int [pk]
  name varchar
  product_id int
  logo int
}

Table collections {
  id int [pk]
  name varchar
}

Table categories {
  id int [pk]
  parent_id int
  collection_id int
  name varchar
}

Table products {
  id int [pk]
  name varchar
  alias varchar
  short_desc varchar
  full_desc text
  price float
  allocated_quantity tinyint
  brand_id int
  discount_id int
  status products_status
}

Table images {
  id int [pk]
  dtype varchar
  metatada json
  model_id int
}

Table tags {
  id int [pk]
  text varchar
  color varchar
}

Table discounts {
  id int [pk]
  code varchar
  name varchar
  desc varchar
  last_updated bigint
  start_time bigint
  end_time bigint
}

Table reviews {
  id int [pk]
  headline varchar
  rating tinyint
  comment varchar
  customer_id int
  product_id int
  last_updated bigint
}

Table option_types { //[{id: 1, name: size}, {id: 2, name: color}, {id: 3, name: feature}]
  id tinyint [pk]
  name varchar
}

Table option_values {
  id tinyint [pk]
  option_type_id tinyint
  name varchar
  value varchar
}

Table attribute_types {
  id tinyint [pk]
  name varchar
}

Table attribute_values {
  id tinyint [pk]
  value varchar
  attribute_type_id int
}


Table product_variants {
  id int [pk]
  sku varchar [note: 'auto create from option values']
  options json [note: 'array']
}

Table wish_lists {
  id int [pk]
  product_id int
  user_id int
}

Table wish_list_items {
  id int [pk]
  wish_list_id int
  product_id int
}

Table shopping_carts {
  id int [pk]
  customer_id int [null]
  session_id varchar
}

Table shopping_cart_items {
  id int [pk]
  cart_id int
  price float
  product_variant_id int
}

Table product_categories {
  id int [pk]
  name varchar
  product_id int
  category_id int
}

Table product_tags {
  id int [pk]
  product_id int
  tag_id int
}

Table product_inventories {
  id int [pk]
  product_variant_id int
  quantity int
  price float
}

//related to orders
Table orders {
  id int [pk]
  customer_id int
  payment_id int
  shipping_detail_id int
  order_time bigint
}

Table order_items {
  id int [pk]
  order_id int
  product_variant_id int
  quantity int
  price float
  sub_total float //!check again
}

Table orders_tracking {
  id int [pk]
  order_id int
  status order_status
  modified_at bigint
  modified_by int
}

Table payments {
  id int [pk]
  method_id int
}

Table payment_methods {
  id int [pk]
  name varchar
  desc varchar
}

Table addresses {
  id int [pk]
  name varchar
}

Table shipping_details {
  id int [pk]
  customer_id int
  first_name varchar
  last_name varchar
  phone_no varchar
  address_id int
}

Table sessions {
  id varchar [pk]
  ip_address varchar(16)
  user_agent varchar(50)
  last_activity int(10)
  user_data text
}

Enum products_status {
  out_of_stock
  in_stock
  running_low [note: 'less than 20']
}

Enum order_status {
  wait_for_verifed
  verified
  on_deliver
  deliver_success
  deliver_failed
}

ref: users.address_id - addresses.id
// ref: users.avatar - images.id
ref: user_roles.username < users.username
ref: user_roles.role_id < roles.id

// ref: brands.logo - images.id
ref: categories.collection_id > collections.id
ref: categories.parent_id < categories.id

ref: products.brand_id > brands.id
ref: products.discount_id > discounts.id

ref: product_inventories.product_variant_id - product_variants.id
ref: product_categories.product_id < products.id
ref: product_categories.category_id < categories.id

ref: product_tags.product_id < products.id
ref: product_tags.tag_id < categories.id

ref: wish_lists.user_id - users.id

ref: wish_list_items.wish_list_id > wish_lists.id
ref: wish_list_items.product_id > products.id

ref: shopping_carts.customer_id - users.id
ref: shopping_carts.session_id - sessions.id

ref: shopping_cart_items.cart_id > shopping_carts.id
ref: shopping_cart_items.product_variant_id > product_variants.id

ref: option_values.option_type_id > option_types.id
ref: attribute_values.attribute_type_id > attribute_types.id

ref: reviews.customer_id > users.id
ref: reviews.product_id > products.id

ref: orders.customer_id > users.id
ref: orders.payment_id - payments.id
ref: orders.shipping_detail_id > shipping_details.id
ref: orders_tracking.order_id - orders.id
ref: orders_tracking.modified_by - users.id

ref: order_items.order_id > orders.id
ref: order_items.product_variant_id > product_variants.id

ref: payments.method_id > payment_methods.id

ref: shipping_details.customer_id > users.id
ref: shipping_details.address_id - addresses.id

ref: images.model_id > products.id
ref: images.model_id - users.id
ref: images.model_id - brands.id

