Table "order" {
  "createdAt" DATETIME(6) [not null, default: `CURRENT_TIMESTAMP(6)`]
  "updatedAt" DATETIME(6) [not null, default: `CURRENT_TIMESTAMP(6)`]
  "code" VARCHAR(255) [not null]
  "state" VARCHAR(255) [not null]
  "active" TINYINT [not null, default: "1"]
  "orderPlacedAt" DATETIME [default: NULL]
  "couponCodes" TEXT [not null]
  "shippingAddress" TEXT [not null]
  "billingAddress" TEXT [not null]
  "currencyCode" VARCHAR(255) [not null]
  "subTotal" INT [not null]
  "subTotalWithTax" INT [not null]
  "shipping" INT [not null, default: "0"]
  "shippingWithTax" INT [not null, default: "0"]
  "id" INT [pk, not null, increment]
  "taxZoneId" INT [default: NULL]
  "customerId" INT [default: NULL]

Indexes {
  customerId
}
}

Table "order_line" {
  "createdAt" DATETIME(6) [not null, default: `CURRENT_TIMESTAMP(6)`]
  "updatedAt" DATETIME(6) [not null, default: `CURRENT_TIMESTAMP(6)`]
  "id" INT [pk, not null, increment]
  "productVariantId" INT [default: NULL]
  "taxCategoryId" INT [default: NULL]
  "featuredAssetId" INT [default: NULL]
  "orderId" INT [default: NULL]

Indexes {
  productVariantId
  taxCategoryId
  featuredAssetId
  orderId
}
}

Table "order_item" {
  "createdAt" DATETIME(6) [not null, default: `CURRENT_TIMESTAMP(6)`]
  "updatedAt" DATETIME(6) [not null, default: `CURRENT_TIMESTAMP(6)`]
  "initialListPrice" INT [default: NULL]
  "listPrice" INT [not null]
  "listPriceIncludesTax" TINYINT [not null]
  "adjustments" TEXT [not null]
  "taxLines" TEXT [not null]
  "cancelled" TINYINT [not null, default: "0"]
  "id" INT [pk, not null, increment]
  "lineId" INT [not null]
  "refundId" INT [default: NULL]

Indexes {
  lineId
  refundId
}
}

Table "fulfillment" {
  "createdAt" DATETIME(6) [not null, default: `CURRENT_TIMESTAMP(6)`]
  "updatedAt" DATETIME(6) [not null, default: `CURRENT_TIMESTAMP(6)`]
  "state" VARCHAR(255) [not null]
  "trackingCode" VARCHAR(255) [not null, default: ""]
  "method" VARCHAR(255) [not null]
  "handlerCode" VARCHAR(255) [not null]
  "id" INT [pk, not null, increment]
}

Table "refund" {
  "createdAt" DATETIME(6) [not null, default: `CURRENT_TIMESTAMP(6)`]
  "updatedAt" DATETIME(6) [not null, default: `CURRENT_TIMESTAMP(6)`]
  "items" INT [not null]
  "shipping" INT [not null]
  "adjustment" INT [not null]
  "total" INT [not null]
  "method" VARCHAR(255) [not null]
  "reason" VARCHAR(255) [default: NULL]
  "state" VARCHAR(255) [not null]
  "transactionId" VARCHAR(255) [default: NULL]
  "metadata" TEXT [not null]
  "id" INT [pk, not null, increment]
  "paymentId" INT [not null]

Indexes {
  paymentId
}
}


Table "order_item_fulfillments_fulfillment" {
  "orderItemId" INT [not null]
  "fulfillmentId" INT [not null]

Indexes {
  orderItemId
  fulfillmentId
  (orderItemId, fulfillmentId) [pk]
}
}




Table "order_modification" {
  "createdAt" DATETIME(6) [not null, default: `CURRENT_TIMESTAMP(6)`]
  "updatedAt" DATETIME(6) [not null, default: `CURRENT_TIMESTAMP(6)`]
  "note" VARCHAR(255) [not null]
  "priceChange" INT [not null]
  "shippingAddressChange" TEXT [default: NULL]
  "billingAddressChange" TEXT [default: NULL]
  "id" INT [pk, not null, increment]
  "orderId" INT [default: NULL]
  "paymentId" INT [default: NULL]
  "refundId" INT [default: NULL]

Indexes {
  paymentId [unique, name: "REL_ad2991fa2933ed8b7f86a71633"]
  refundId [unique, name: "REL_cb66b63b6e97613013795eadbd"]
  orderId
}
}

Table "order_modification_order_items_order_item" {
  "orderModificationId" INT [not null]
  "orderItemId" INT [not null]

Indexes {
  orderModificationId
  orderItemId
  (orderModificationId, orderItemId) [pk]
}
}

Table "promotion" {
  "createdAt" DATETIME(6) [not null, default: `CURRENT_TIMESTAMP(6)`]
  "updatedAt" DATETIME(6) [not null, default: `CURRENT_TIMESTAMP(6)`]
  "deletedAt" DATETIME [default: NULL]
  "startsAt" DATETIME [default: NULL]
  "endsAt" DATETIME [default: NULL]
  "couponCode" VARCHAR(255) [default: NULL]
  "perCustomerUsageLimit" INT [default: NULL]
  "name" VARCHAR(255) [not null]
  "enabled" TINYINT [not null]
  "conditions" TEXT [not null]
  "actions" TEXT [not null]
  "priorityScore" INT [not null]
  "id" INT [pk, not null, increment]
}

Table "order_promotions_promotion" {
  "orderId" INT [not null]
  "promotionId" INT [not null]

Indexes {
  orderId
  promotionId
  (orderId, promotionId) [pk]
}
}

Table "surcharge" {
  "createdAt" DATETIME(6) [not null, default: `CURRENT_TIMESTAMP(6)`]
  "updatedAt" DATETIME(6) [not null, default: `CURRENT_TIMESTAMP(6)`]
  "description" VARCHAR(255) [not null]
  "listPrice" INT [not null]
  "listPriceIncludesTax" TINYINT [not null]
  "sku" VARCHAR(255) [not null]
  "taxLines" TEXT [not null]
  "id" INT [pk, not null, increment]
  "orderId" INT [default: NULL]
  "orderModificationId" INT [default: NULL]

Indexes {
  orderId
  orderModificationId
}
}

Table "stock_movement" {
  "createdAt" DATETIME(6) [not null, default: `CURRENT_TIMESTAMP(6)`]
  "updatedAt" DATETIME(6) [not null, default: `CURRENT_TIMESTAMP(6)`]
  "type" VARCHAR(255) [not null]
  "quantity" INT [not null]
  "id" INT [pk, not null, increment]
  "discriminator" VARCHAR(255) [not null]
  "productVariantId" INT [default: NULL]
  "orderItemId" INT [default: NULL]
  "orderLineId" INT [default: NULL]

Indexes {
  discriminator
  productVariantId
  orderItemId
  orderLineId
}
}

Ref:"order"."id" < "order_line"."orderId" [delete: cascade]
Ref:"order"."id" < "surcharge"."orderId" [delete: cascade]
Ref:"order"."id" < "history_entry"."orderId" [delete: cascade]
Ref:"order"."id" < "order_promotions_promotion"."orderId" [update: cascade, delete: cascade]
Ref:"order"."id" < "order_modification"."orderId" [delete: cascade]
Ref:"order"."customerId" > "customer"."id"

Ref:"order_item"."id" < "stock_movement"."orderItemId"
Ref:"order_item"."id" < "order_modification_order_items_order_item"."orderItemId" [update: cascade, delete: cascade]
Ref:"order_item"."id" < "order_item_fulfillments_fulfillment"."orderItemId" [update: cascade, delete: cascade]

Ref: "stock_movement"."productVariantId" > "product_variant"."id"
Ref:"order_line"."id" < "stock_movement"."orderLineId"
Ref:"order_line"."id" < "order_item"."lineId" [delete: cascade]
Ref:"order_line"."featuredAssetId" > "asset"."id"
Ref:"order_line"."productVariantId" > "product_variant"."id"

Ref:"order_modification"."id" < "surcharge"."orderModificationId"
Ref:"order_modification"."id" < "order_modification_order_items_order_item"."orderModificationId" [update: cascade, delete: cascade]

Ref:"refund"."id" < "order_item"."refundId"
Ref:"refund"."id" < "order_modification"."refundId"

Ref:"payment"."id" < "refund"."paymentId"
Ref:"payment"."id" < "order_modification"."paymentId"

Ref:"promotion"."id" < "order_promotions_promotion"."promotionId" [update: cascade, delete: cascade]

Ref:"fulfillment"."id" < "order_item_fulfillments_fulfillment"."fulfillmentId"

TableGroup order{
    order
    order_line
    order_item
    // refund
    // fulfillment
    // order_item_fulfillments_fulfillment
    // order_modification
    // order_modification_order_items_order_item
    // promotion
    // order_promotions_promotion
    // surcharge
    stock_movement
}

TableGroup fulfillment {
    fulfillment
    order_item_fulfillments_fulfillment
}

TableGroup order_modification {
    order_modification
    order_modification_order_items_order_item
}

TableGroup promotion {
    promotion
    order_promotions_promotion
}

TableGroup later {
    refund
    surcharge
}

TableGroup mockTable {
    history_entry
    customer
    product_variant
    asset
    payment
}

Table product_variant {
    id int
}

Table asset {
    id int
}

Table payment {
    id int
}

Table customer {
    id int
}

Table history_entry {
    id int
    orderId int
}
// Ref:"tax_category"."id" < "order_line"."taxCategoryId"